# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetGreen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GetGreen
	pod ’SnapKit’
	pod ‘Firebase’
	pod ‘Alamofire’
	pod 'Firebase/Core'
  	pod 'Firebase/Auth'
	pod 'Firebase/Database'

  target 'GetGreenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
